name: Agent Runner
on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      issue: { description: "Issue number", required: true }

jobs:
  run-agent:
    if: (github.event_name == 'issues' && github.event.label.name == 'agent:ready') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@v4

      - name: Select issue
        id: pick
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const { context, getOctokit } = require('@actions/github');
            const issueNumber = context.payload.inputs?.issue ?? context.payload.issue?.number;
            core.setOutput('issue', issueNumber);

      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'npm' }
      - run: npm ci
      - name: Run agent (makes changes locally)
        run: node tools/agent/run.js ${{ steps.pick.outputs.issue }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: agent/issue-${{ steps.pick.outputs.issue }}
          title: "Agent: resolve issue #${{ steps.pick.outputs.issue }}"
          commit-message: "feat(agent): apply changes for issue #${{ steps.pick.outputs.issue }}"
          body: |
            Automated changes for issue #${{ steps.pick.outputs.issue }}.
            - [ ] Owner to review
            - [ ] CI green
            - [ ] Preview link added
          labels: from:agent